version: "3"

services:
  aluno:
    container_name: api-aluno
    build:
      dockerfile: Dockerfile
      context: ./api-aluno/
    ports:
      - "8081:8081"
    restart: always
    networks:
      - app-network
  professor:
    container_name: api-professor
    build:
      dockerfile: Dockerfile
      context: ./api-professor/
    ports:
      - "8082:8082"
    restart: always
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
    external: true
